# named volumes:
volumes:
  world-db:

services:
  db:
    image: "mariadb:latest"
    volumes:
      # without volumes, data would be reset everytime
      # named volumes:
      - world-db:/var/lib/mysql
      # local volumes
      #- ./conf/mysql:/etc/mysql/conf.d
      #- ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_USER}"

  web:
    # build specifies the location of a custom Dockerfile
    build: ./web
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      # without volumes, data would be reset everytime
      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./web/html:/var/www/html
    environment:
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASSWORD}"